http_listen: '0.0.0.0:1229'
hoster: Josh's Couch Computer

# TODO: try setting this to 0
tracker_update_interval_mins: 1

# We're behind nginx using `proxy_set_header X-Real-IP $remote_addr`.
client_ip_source: XRealIp

upstream_trackers:
  # http://127.0.0.1:1234/tracker/AAAAAAAAAAAAAAAAAAAAAA
  # http://127.0.0.1:1235/tracker/$(python3 -c 'import base64, random; print(base64.urlsafe_b64encode(random.randbytes(16))[:-2].decode("utf8"))')
  # echo -n "http://127.0.0.1:1236/tracker/$(python3 -c 'import base64, random; print(base64.urlsafe_b64encode(random.randbytes(16))[:-2].decode("utf8"))')" | gtkclip
  - http://127.0.0.1:1231/tracker
  - http://127.0.0.1:1232/tracker
  - http://127.0.0.1:1233/tracker
  - http://127.0.0.1:1234/tracker
  - http://127.0.0.1:1235/tracker
  - http://127.0.0.1:1236/tracker
  - http://127.0.0.1:1237/tracker
  - http://127.0.0.1:1238/tracker
  - http://127.0.0.1:1239/tracker

cors_permissive: false
banners: []
database:
  type: postgres
  connection_string: 'postgresql://cheesetrackers:cheesetrackers@127.0.0.1:5433/cheesetrackers'

# Unused auth and Discord things
token:
  secret: changeme
  issuer: 'example.com'
  validity_duration_days: 90
discord:
  # Discord app client ID.
  client_id: 0
  # Discord app secret.
  client_secret: ''
  # Cipher key used to encrypt the continuation token.  This must be a
  # base64-encoded sequence of 32 bytes randomly generated from a
  # cryptographically secure PRNG.
  token_cipher_key: TFEJUY7FwIvxTi2DnNIrI3nITO4Dyrrw4TKD0w2zRPM=
public_url: 'https://example.com/'
